EncryptionKeyChunk: Don't try to parse too big values as Integer
IVs can be way too big for integer, resulting in exceptions like
NumberFormatException: Invalid int: "8bebc5019dd7301db52130f579d42f8c"

Instead of parsing as an int and formatting the parsed int as String
to do zero padding, pad as String and convert the result char by
char to construct the padded IV byte[] representation.

Signed-off-by: Jonas Larsson <jonas@hallerud.se>